### ISSUE TITLE
torch vision problem

### ISSUE THREAD

**Issue by zhuzhen1996** [sowmen/face-cutout#1]
Hello! My pytorch version is 1.4, but it cannot be installed when pretrained and torch_optimizer are installed as required. I see that torch>=1.4 in your request, do you need a higher version of torch?

**Comment by sowmen** [comment]
Yes, any latest torch version should work. My updated version was torch 1.7

**Comment by zhuzhen1996** [comment]
Thank you very much for your prompt reply! I changed to torch==1.8 to solve the above problem.
